import Foundation

public enum TranscriptParser {
  public static func parse(fileURL: URL) -> ParsedSession {
    let iso = ISO8601DateFormatter()
    let sessionID = fileURL.deletingPathExtension().lastPathComponent
    guard let content = try? String(contentsOf: fileURL, encoding: .utf8) else {
      return ParsedSession(sessionID: sessionID, cwd: nil, startedAt: nil, endedAt: nil,
                           userPromptCount: 0, messages: [])
    }

    var cwd: String?
    var messages: [TranscriptMessage] = []
    var timestamps: [Date] = []
    var userPrompts = 0
    var nextIndex = 0

    for line in content.split(separator: "\n", omittingEmptySubsequences: true) {
      guard let data = line.data(using: .utf8),
            let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
      else { continue }   // defensive: skip garbage lines

      if cwd == nil, let c = obj["cwd"] as? String { cwd = c }
      let timestamp = (obj["timestamp"] as? String).flatMap(iso.date(from:))
      if let timestamp { timestamps.append(timestamp) }

      let type = obj["type"] as? String
      let message = obj["message"] as? [String: Any]
      let role = (message?["role"] as? String) ?? (type ?? "unknown")
      let content = message?["content"]
      let text = extractText(content)
      if type == "user" { userPrompts += 1 }
      let isUserPrompt = (type == "user") && !isToolResult(content) && !isInjectedOrCommand(text) && !text.isEmpty
      if !text.isEmpty {
        messages.append(TranscriptMessage(index: nextIndex, role: role, text: text,
                                          timestamp: timestamp, isUserPrompt: isUserPrompt))
        nextIndex += 1
      }
    }

    return ParsedSession(
      sessionID: sessionID, cwd: cwd,
      startedAt: timestamps.min(), endedAt: timestamps.max(),
      userPromptCount: userPrompts, messages: messages)
  }

  /// `content` is either a String or an array of content blocks (`{type:text,text:...}`).
  private static func extractText(_ content: Any?) -> String {
    if let s = content as? String { return s }
    if let blocks = content as? [[String: Any]] {
      return blocks.compactMap { $0["text"] as? String }.joined(separator: "\n")
    }
    return ""
  }

  /// True when a `type:"user"` record is actually a tool result, not human prose.
  private static func isToolResult(_ content: Any?) -> Bool {
    guard let blocks = content as? [[String: Any]] else { return false }
    return blocks.contains { ($0["type"] as? String) == "tool_result" }
  }

  /// True when `text` carries structural markers of a slash-command invocation or
  /// injected context, rather than genuine human prose.
  private static func isInjectedOrCommand(_ text: String) -> Bool {
    let markers = [
      "<command-name>", "<command-message>", "<command-args>",
      "<local-command-stdout>", "<local-command-stderr>",
      "<bash-input>", "<bash-stdout>", "<system-reminder>",
      "Caveat: The messages below were generated by the user while running local commands",
    ]
    return markers.contains { text.contains($0) }
  }
}
