import Foundation

/// The shared harness-tag vocabulary — deliberately **two members, not one list**.
///
/// `injectionMarkers` feeds `TranscriptParser.isInjectedOrCommand`, which gates `isUserPrompt`,
/// which gates what is eligible to become a loose end at all (`LooseEndExtractor`) and what the
/// trust gate will verify (`LooseEndVerifier`). `harnessTagNames` feeds the renderer
/// (`TranscriptMarkup`).
///
/// A single shared list would be wrong twice over. The shapes differ — the gate matches a closing
/// tag (`</tool_uses>`), a prefix (`<subagent`), and two prose sentences, none of which the scanner
/// can scan forward from. And a shared list would let a tag added for **display** silently change
/// **extraction**. Keeping them separate, with `TranscriptVocabularyTests` pinning the gate list,
/// means rendering can grow freely while the trust gate stays frozen.
public enum TranscriptVocabulary {
  /// Bare tag names the renderer recognises. The scanner composes `<name>` / `</name>` itself.
  /// Safe to extend: adding a name here changes display only.
  public static let harnessTagNames: [String] = [
    "command-name", "command-message", "command-args",
    "local-command-stdout", "local-command-stderr", "local-command-caveat",
    "bash-input", "bash-stdout",
    "system-reminder", "task-notification",
    "tool_uses", "tool_use_error",
  ]

  /// Harness tags with no exact `<tag>` entry in `injectionMarkers`, each for a recorded reason.
  /// An exemption is a statement that the gate's behavior for this tag is intentional.
  ///
  /// - `local-command-caveat`: gated upstream by its **prose** form ("Caveat: The messages
  ///   below…"), which is what Claude Code actually emits alongside the tag.
  /// - `tool_use_error`: never gated (2 occurrences in parser-visible input); it is display-only.
  /// - `tool_uses`: gated by its **closing** tag `</tool_uses>`, not its opening tag.
  public static let gateExemptTagNames: Set<String> = [
    "local-command-caveat", "tool_use_error", "tool_uses",
  ]

  /// **FROZEN — do not edit as part of a rendering change.** Substrings that mark a `type:"user"`
  /// record as machine-authored. Moved here verbatim from `TranscriptParser.isInjectedOrCommand`;
  /// `TranscriptVocabularyTests` pins the exact contents.
  public static let injectionMarkers: [String] = [
    "<command-name>", "<command-message>", "<command-args>",
    "<local-command-stdout>", "<local-command-stderr>",
    "<bash-input>", "<bash-stdout>", "<system-reminder>",
    "<task-notification>", "</tool_uses>", "<subagent",
    "[Request interrupted",
    "Base directory for this skill:",
    "Caveat: The messages below were generated by the user while running local commands",
  ]
}
