import Foundation
import Testing
@testable import PensieveKit

/// The trust-gate pin. `injectionMarkers` feeds `isInjectedOrCommand` → `isUserPrompt` →
/// `LooseEndExtractor` and `LooseEndVerifier`. This literal is the pre-change list, copied
/// byte-for-byte. If a future rendering change edits the vocabulary, THIS fails — which is the
/// entire point of splitting the vocabulary into two members.
@Test func injectionMarkersAreUnchangedFromTheTrustGateBaseline() {
  #expect(TranscriptVocabulary.injectionMarkers == [
    "<command-name>", "<command-message>", "<command-args>",
    "<local-command-stdout>", "<local-command-stderr>",
    "<bash-input>", "<bash-stdout>", "<system-reminder>",
    "<task-notification>", "</tool_uses>", "<subagent",
    "[Request interrupted",
    "Base directory for this skill:",
    "Caveat: The messages below were generated by the user while running local commands",
  ])
}

/// Every renderable harness tag is either gated by an exact `<tag>` marker or explicitly
/// documented as exempt. Adding a tag to `harnessTagNames` without deciding its gate status
/// fails here rather than silently widening or narrowing extraction.
@Test func everyHarnessTagNameHasAnExplicitGateDecision() {
  for name in TranscriptVocabulary.harnessTagNames {
    let gated = TranscriptVocabulary.injectionMarkers.contains("<\(name)>")
    let exempt = TranscriptVocabulary.gateExemptTagNames.contains(name)
    #expect(gated || exempt, "harness tag '\(name)' has no gate decision")
  }
}

/// Exemptions must be real tags, not typos that would silently excuse a missing gate entry.
@Test func gateExemptionsReferenceRealHarnessTags() {
  for name in TranscriptVocabulary.gateExemptTagNames {
    #expect(TranscriptVocabulary.harnessTagNames.contains(name), "stale exemption '\(name)'")
  }
}

/// Tag names are bare — the scanner builds `<name>` / `</name>` itself.
@Test func harnessTagNamesCarryNoAngleBrackets() {
  for name in TranscriptVocabulary.harnessTagNames {
    #expect(!name.contains("<") && !name.contains(">"))
  }
}
